"""make product_id nullable, add custom_name

Revision ID: 74840bcf89f9
Revises: b7a0b6463fda
Create Date: 2026-05-25 21:21:54.490144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74840bcf89f9'
down_revision: Union[str, Sequence[str], None] = 'b7a0b6463fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_items', sa.Column('custom_name', sa.String(length=255), nullable=True))
    op.alter_column('sale_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_items', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('sale_items', 'custom_name')
    # ### end Alembic commands ###
