"""initial_schema

Revision ID: b7a0b6463fda
Revises: 
Create Date: 2026-05-25 19:45:21.099980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a0b6463fda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_uuid'), 'categories', ['uuid'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=True)
    op.create_index(op.f('ix_employees_uuid'), 'employees', ['uuid'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('low_stock_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_product_category', 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_uuid'), 'products', ['uuid'], unique=True)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('warranty_info', sa.String(length=255), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sale_created', 'sales', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_sale_customer', 'sales', ['customer_name'], unique=False)
    op.create_index('idx_sale_seller', 'sales', ['seller_id'], unique=False)
    op.create_index(op.f('ix_sales_uuid'), 'sales', ['uuid'], unique=True)
    op.create_table('weekly_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_week', sa.String(length=10), nullable=False),
    sa.Column('total_sales', sa.Float(), nullable=False),
    sa.Column('completed_repairs', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_snapshot_employee', 'weekly_snapshots', ['employee_id'], unique=False)
    op.create_index('idx_snapshot_week', 'weekly_snapshots', ['snapshot_week'], unique=False)
    op.create_index(op.f('ix_weekly_snapshots_uuid'), 'weekly_snapshots', ['uuid'], unique=True)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('imei', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('desperfecto', sa.String(length=500), nullable=False),
    sa.Column('diagnostico', sa.String(length=500), nullable=True),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('warranty_info', sa.String(length=255), nullable=True),
    sa.Column('assigned_technician_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wo_assigned_tech', 'work_orders', ['assigned_technician_id'], unique=False)
    op.create_index('idx_wo_brand_model', 'work_orders', ['brand', 'model'], unique=False)
    op.create_index('idx_wo_created_at', 'work_orders', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_wo_customer_name', 'work_orders', ['customer_name'], unique=False)
    op.create_index('idx_wo_imei', 'work_orders', ['imei'], unique=False)
    op.create_index('idx_wo_phone', 'work_orders', ['phone_number'], unique=False)
    op.create_index('idx_wo_status', 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_uuid'), 'work_orders', ['uuid'], unique=True)
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sale_item_product', 'sale_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_sale_items_uuid'), 'sale_items', ['uuid'], unique=True)
    op.create_table('work_order_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('from_employee_id', sa.Integer(), nullable=True),
    sa.Column('to_employee_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['to_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_assignments_uuid'), 'work_order_assignments', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_assignments_uuid'), table_name='work_order_assignments')
    op.drop_table('work_order_assignments')
    op.drop_index(op.f('ix_sale_items_uuid'), table_name='sale_items')
    op.drop_index('idx_sale_item_product', table_name='sale_items')
    op.drop_table('sale_items')
    op.drop_index(op.f('ix_work_orders_uuid'), table_name='work_orders')
    op.drop_index('idx_wo_status', table_name='work_orders')
    op.drop_index('idx_wo_phone', table_name='work_orders')
    op.drop_index('idx_wo_imei', table_name='work_orders')
    op.drop_index('idx_wo_customer_name', table_name='work_orders')
    op.drop_index('idx_wo_created_at', table_name='work_orders')
    op.drop_index('idx_wo_brand_model', table_name='work_orders')
    op.drop_index('idx_wo_assigned_tech', table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_weekly_snapshots_uuid'), table_name='weekly_snapshots')
    op.drop_index('idx_snapshot_week', table_name='weekly_snapshots')
    op.drop_index('idx_snapshot_employee', table_name='weekly_snapshots')
    op.drop_table('weekly_snapshots')
    op.drop_index(op.f('ix_sales_uuid'), table_name='sales')
    op.drop_index('idx_sale_seller', table_name='sales')
    op.drop_index('idx_sale_customer', table_name='sales')
    op.drop_index('idx_sale_created', table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_products_uuid'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index('idx_product_category', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_employees_uuid'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_categories_uuid'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
