"""add is definitive to weekly snapshots

Revision ID: ef5fd6b9d5c8
Revises: e5f4a3b2c1d0
Create Date: 2026-07-06 20:04:01.974800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef5fd6b9d5c8'
down_revision: Union[str, Sequence[str], None] = 'e5f4a3b2c1d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('weekly_snapshots', sa.Column('is_definitive', sa.Boolean(), nullable=True))
    # Set all existing rows to False
    op.execute("UPDATE weekly_snapshots SET is_definitive = 0 WHERE is_definitive IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_snapshots', 'is_definitive')
    # ### end Alembic commands ###
